name: Bug report
description: Report bugs with the engine here
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe your bug here."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: "Steps to reproduce this bug."
    validations:
      required: true

  - type: textarea
    id: terminal
    attributes:
      label: "Command Prompt/Terminal logs"
      render: bash
    validations:
      required: false

  - type: dropdown
    id: modding
    attributes:
      label: "Have you modified the Source Code?"
      options:
        - Yes.
        - No.
    validations:
      required: true

  - type: input
    id: buildsummary
    attributes:
      label: "Have you modded the build in any way?"
      placeholder: "(I edited ClientPrefs.hx and tried to add a new setting.)\n(This mod <url here> is crashing)"
    validations:
      required: false

  - type: dropdown
    id: btarget
    attributes:
      label: "What is your platform?"
      options:
        - "Windows"
        - "Linux"
        - "MacOS"
        - "Not in this list (WILL BE CLOSED)"
    validations:
      required: true
