name: Build

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      os:
        required: true
        type: string
      setupCommand:
        required: true
        type: string
      buildArgs:
        required: true
        type: string
      artifactName:
        required: true
        type: string
      artifactPath:
        required: true
        type: string
      doCache:
        required: true
        type: string

env:
  HAXE_VERSION: 4.3.6
  PROJECT_NAME: PsychExtendedOnline

jobs:
  build:
    name: Build
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: ${{ env.HAXE_VERSION }}

      - name: Install libVLC
        if: startsWith(inputs.name, 'Linux')
        run: sudo apt install libvlc-dev libvlccore-dev

      - name: Restore cache for android builds
        if: endsWith(inputs.doCache, 'YES')
        uses: actions/cache@v4
        with:
          key: cache-build-${{ inputs.name }}
          path: |
            ~/.gradle
            .haxelib/
            /home/runner/haxelib/
            /Users/runner/haxelib/
            C:/hostedtoolcache/windows/haxe/4.3.6/x64/lib/
            ~/.haxelib/
            export/release/android/haxe/
            export/release/android/obj/
            export/release/ios/${{ env.PROJECT_NAME }}/haxe/
            export/release/ios/${{ env.PROJECT_NAME }}/obj/
            export\release\windows\haxe\
            export\release\windows\obj\
            .haxelib\
          restore-keys: |
            cache-build-${{ inputs.name }}

      - name: Install Libraries (ANGLE)
        if: endsWith(inputs.name, 'ANGLE')
        run: |
          ${{ inputs.setupCommand }}
          haxelib remove funkin.vis --quiet
          haxelib git funkin.vis https://github.com/FunkinCrew/funkVis 1966f8fbbbc509ed90d4b520f3c49c084fc92fd6 --quiet

      - name: Install Libraries (NORMAL)
        if: endsWith(inputs.name, 'NORMAL')
        run: |
          haxelib install hmm --quiet
          haxelib run hmm install --quiet
          haxelib remove funkin.vis --quiet
          haxelib git funkin.vis https://github.com/FunkinCrew/funkVis 1966f8fbbbc509ed90d4b520f3c49c084fc92fd6 --quiet

      - name: Configure Android
        if: startsWith(inputs.name, 'Android')
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME_21_X64
          haxelib run lime config ANDROID_SETUP true

      - name: Compile
        run: haxelib run lime build ${{ inputs.buildArgs }}

      - name: Make IPA
        if: startsWith(inputs.name, 'iOS')
        run: |
          brew install ldid
          cd export/release/ios/build/Release-iphoneos/${{ env.PROJECT_NAME }}.app
          ldid -S../../../${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.entitlements ${{ env.PROJECT_NAME }}
          cd ..
          mkdir Payload
          mv ${{ env.PROJECT_NAME }}.app Payload
          zip -r ${{ env.PROJECT_NAME }}.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: ${{ inputs.artifactName }}
          path: ${{ inputs.artifactPath }}
          if-no-files-found: error

      - name: Clear Old Cache
        if: endsWith(inputs.doCache, 'YES')
        uses: actions/github-script@v7
        continue-on-error: true # Don't break the build if deletion fails
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              if (cache.key == "cache-build-${{ inputs.name }}") {
                console.log('Clearing ' + cache.key + '...')
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
                console.log("Cache cleared.")
              }
            }
            
      - name: Uploading new cache
        if: endsWith(inputs.doCache, 'YES')
        uses: actions/cache@v4
        with:
          # caching again since for some reason it doesnt work with the first post cache shit
          key: cache-build-${{ inputs.name }}
          path: |
            ~/.gradle
            .haxelib/
            /home/runner/haxelib/
            /Users/runner/haxelib/
            C:/hostedtoolcache/windows/haxe/4.3.6/x64/lib/
            ~/.haxelib/
            export/release/android/haxe/
            export/release/android/obj/
            export/release/ios/${{ env.PROJECT_NAME }}/haxe/
            export/release/ios/${{ env.PROJECT_NAME }}/obj/
            export\release\windows\haxe\
            export\release\windows\obj\
            .haxelib\
          restore-keys: |
            cache-build-${{ inputs.name }}